inherits = "dark_plus"

# UI tweaks (transparent background, color adjustment)
"ui.background" = { bg = "none" }
"ui.statusline" = { bg = "none" }
"ui.bufferline.active" = { bg = "#245b57" }
"ui.bufferline.background" = { bg = "none" }

# Highlight fuzzy-find search text
"special" = { modifiers = ["dim"] }
