theme = "custom"

[editor]
mouse = false
completion-trigger-len = 1
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.file-picker]
hidden = false
