theme = "custom"

[editor]
mouse = true
completion-trigger-len = 1
bufferline = "always"
end-of-line-diagnostics = "disable"
continue-comments = false

  [editor.cursor-shape]
  insert = "bar"
  normal = "block"
  select = "underline"

  [editor.soft-wrap]
  enable = true
  wrap-indicator = ""

  [editor.file-picker]
  hidden = false

  [editor.inline-diagnostics]
  cursor-line = "disable"
  other-lines = "disable"
