# Are all the 'auto-format' statements needed?

# LSP Settings

[language-server.ltex-ls.config.ltex]
language = "en-GB"
additionalRules.enablePickyRules = true
disabledRules = { "en-GB" = [
  "PROFANITY",
  "DASH_RULE",
  "TWO_HYPHENS",
  "PLUS_MINUS",
  "ELLIPSIS",
  "EN_QUOTES",
], "de-CH" = [
  "TYPOGRAFISCHE_ANFUEHRUNGSZEICHEN_CH",
  "TYPOGRAFISCHE_APOSTROPHE",
  "MULTIPLICATION_SIGN",
  "ABKUERZUNG_LEERZEICHEN",
  "AUSLASSUNGSPUNKTE",
] }
latex.commands = { "\\gls{}" = "default" }

[[language-server.jdtls.config.java]]
format = { enabled = true }

# Language Behaviour

[[language]]
name = "handlebars"
scope = "source.hbs"
file-types = ["hbs"]
formatter = { command = "prettier", args = [
  "--parser",
  "glimmer",
  "--use-tabs",
] }
auto-format = true

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-lsp"]

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls"]
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--use-tabs",
] }
auto-format = true

[[language]]
name = "latex"
language-servers = ["texlab", "ltex-ls"]
formatter = { command = "latexindent", args = ["-g=/tmp/"] }
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "bash"
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "yamlfmt", args = [
  "-formatter",
  "retain_line_breaks=true,scan_folded_as_literal=true",
  "-",
] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html", "--use-tabs"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css", "--use-tabs"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = [
  "--parser",
  "typescript",
  "--use-tabs",
] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = [
  "--parser",
  "typescript",
  "--use-tabs",
] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = [
  "format",
  "--option",
  "indent_tables=true",
  "-",
] }
auto-format = true

[[language]]
name = "java"
auto-format = true

[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "python"
auto-format = true

[[language]]
name = "sql"
formatter = { command = "pg_format", args = ["-"] }
auto-format = true

[[language]]
name = "nasm"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
