# Are all the 'auto-format' statements needed?

[[language]]
name = "go"
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls"]
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--use-tabs",
] }
auto-format = true

[[language]]
name = "latex"
language-servers = ["texlab", "ltex-ls"]
formatter = { command = "latexindent", args = ["-g=/tmp/"] }
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "bash"
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "yamlfmt", args = [
  "-formatter",
  "include_document_start=true,indentless_arrays=true,retain_line_breaks=true,scan_folded_as_literal=true",
  "-",
] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html", "--use-tabs"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css", "--use-tabs"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = [
  "--parser",
  "typescript",
  "--use-tabs",
] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "java"
auto-format = true

[[language-server.jdtls.config.java]]
format = { enabled = true }

[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "python"
auto-format = true
