# Do these also work when the first LSP is not installed? See after release.

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]

[[language]]
name = "latex"
language-servers = [ "texlab", "ltex-ls" ]
formatter = { command = "latexindent" }
auto-format = true

[[language]]
name = "bash"
formatter = { command = "shfmt" }
auto-format = true
