# Languages

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-lsp"]
formatter = { command = "goimports" }
auto-format = true

[language-server.golangci-lint-lsp.config]
command = [
  "golangci-lint",
  "run",
  "--output.json.path=stdout",
  "--show-stats=false",
  "--issues-exit-code=1",
]

[[language]]
name = "bash"
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "python"
auto-format = true

# Documentation

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls-plus"]
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--use-tabs",
] }
auto-format = true

[[language]]
name = "latex"
language-servers = ["texlab", "ltex-ls-plus"]
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "latexindent", args = ["--cruft=/tmp/"] }
# Switch to `tex-fmt` as soon as tables are supported
# formatter = { command = "tex-fmt", args = ["--stdin", "--nowrap", "--usetabs", "--tabsize", "1"] }
auto-format = true

[language-server.ltex-ls-plus.config.ltex]
language = "en-GB"
additionalRules.enablePickyRules = true
disabledRules = { "en-GB" = [
  "PROFANITY",
  "DASH_RULE",
  "TWO_HYPHENS",
  "PLUS_MINUS",
  "ELLIPSIS",
  "EN_QUOTES",
], "de-CH" = [
  "TYPOGRAFISCHE_ANFUEHRUNGSZEICHEN_CH",
  "TYPOGRAFISCHE_APOSTROPHE",
  "MULTIPLICATION_SIGN",
  "ABKUERZUNG_LEERZEICHEN",
  "AUSLASSUNGSPUNKTE",
] }
latex.commands = { "\\gls{}" = "default" }

# Config

# trim_trailing_whitespace fix: https://github.com/google/yamlfmt/issues/185#issuecomment-2186961227
[[language]]
name = "yaml"
formatter = { command = "yamlfmt", args = [
  "-formatter",
  "retain_line_breaks=true,scan_folded_as_literal=true,trim_trailing_whitespace=true",
  "-",
] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = [
  "format",
  "--option",
  "indent_tables=true",
  "-",
] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json", "--use-tabs"] }
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixfmt" }

[[language]]
name = "hcl"
formatter = { command = "tofu", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "tfvars"
formatter = { command = "tofu", args = ["fmt", "-"] }
auto-format = true

# Web

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html", "--use-tabs"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css", "--use-tabs"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = [
  "--parser",
  "typescript",
  "--use-tabs",
] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = [
  "--parser",
  "typescript",
  "--use-tabs",
] }
auto-format = true

[[language]]
name = "handlebars"
scope = "source.hbs"
file-types = ["hbs"]
formatter = { command = "prettier", args = [
  "--parser",
  "glimmer",
  "--use-tabs",
] }
auto-format = true
# Experimental

[[language]]
name = "java"
auto-format = true

[[language-server.jdtls.config.java]]
format = { enabled = true }

[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "nasm"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "alloy"
scope = "source.alloy"
injection-regex = "alloy"
file-types = ["alloy"]
indent = { tab-width = 2, unit = "\t" }
comment-token = "//"
grammar = "hcl"
formatter = { command = "alloy", args = ["fmt", "-"] }
auto-format = true
